# Generated by Django 6.0.7 on 2026-07-17 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tavern', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='UserAIProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lora_path', models.CharField(default='outputs/checkpoint-60', help_text='專屬 LoRA 模型資料夾路徑', max_length=255)),
                ('system_prompt', models.TextField(default='你是個好助手...', help_text='專屬創世聖經與絕對鐵律')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
