# Generated by Django 6.0.7 on 2026-07-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tavern', '0002_alter_chapter_title_alter_message_role_useraiprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='system_prompt',
            field=models.TextField(blank=True, help_text='此章節專屬的 AI 創作風格/人設設定 (留空則使用預設設定)', null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10),
        ),
        migrations.DeleteModel(
            name='UserAIProfile',
        ),
    ]
