# Generated by Django 6.0.7 on 2026-07-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tavern', '0003_chapter_system_prompt_alter_chapter_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='memory',
            field=models.TextField(blank=True, help_text='長效記憶：角色設定、前傳背景、核心伏筆等', null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='system_prompt',
            field=models.TextField(blank=True, help_text='此章節專屬的 AI 創作風格/人設設定', null=True),
        ),
    ]
