# Generated by Django 6.0.7 on 2026-07-22 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tavern', '0004_chapter_memory_alter_chapter_system_prompt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='memory',
            field=models.TextField(blank=True, help_text='單章記憶：本章當前劇情與短期動態', null=True),
        ),
        migrations.CreateModel(
            name='GlobalMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, help_text='全域角色與世界觀設定（所有故事線共用）', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='global_memory', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
