# Generated by Django 6.0.7 on 2026-07-27 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tavern', '0006_loramodel_chapter_lora'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='loramodel',
            name='description',
            field=models.TextField(blank=True, help_text='風格說明', null=True),
        ),
        migrations.AlterField(
            model_name='loramodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loras', to=settings.AUTH_USER_MODEL),
        ),
    ]
