# Generated by Django 6.0.7 on 2026-07-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tavern', '0007_alter_loramodel_description_alter_loramodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='loramodel',
            name='system_prompt',
            field=models.TextField(blank=True, help_text='此 LoRA 靈魂搭配的預設 System Prompt 人設', null=True),
        ),
        migrations.AlterField(
            model_name='loramodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loramodel',
            name='folder_path',
            field=models.CharField(max_length=255),
        ),
    ]
